import { FieldConfig } from '../../../models/region.model';
import {
  UK_BAGGAGE_FIELDS,
  UK_CARD_MISUSE_FIELDS,
  UK_EVACUATION_FIELDS,
  UK_MEDICAL_FIELDS,
  UK_OTHERS_FIELDS,
  UK_RENTAL_VEHICLE_FIELDS,
  UK_TRIP_CANCEL_FIELDS,
} from './field-sets';

export const UK_CORP_TRAVEL_CLAIM_FIELDS: Record<string, FieldConfig[]> = {
  TRIP_CANCEL: UK_TRIP_CANCEL_FIELDS,
  BAGGAGE: UK_BAGGAGE_FIELDS,
  RENTAL_VEHICLE: UK_RENTAL_VEHICLE_FIELDS,
  EVACUATION: UK_EVACUATION_FIELDS,
  MEDICAL: UK_MEDICAL_FIELDS,
  CARD_MISUSE: UK_CARD_MISUSE_FIELDS,
  OTHERS: UK_OTHERS_FIELDS,
};
