import { FieldConfig } from '../../../models/region.model';
import {
  AME_BAGGAGE_FIELDS,
  AME_EVACUATION_FIELDS,
  AME_MEDICAL_FIELDS,
  AME_OTHERS_FIELDS,
  AME_PA_WEEKLY_FIELDS,
  AME_PS_WEEKLY_FIELDS,
  AME_RENTAL_VEHICLE_FIELDS,
  AME_TRIP_CANCEL_FIELDS,
} from './field-sets';

export const AME_CORP_TRAVEL_CLAIM_FIELDS: Record<string, FieldConfig[]> = {
  TRIP_CANCEL: AME_TRIP_CANCEL_FIELDS,
  BAGGAGE: AME_BAGGAGE_FIELDS,
  RENTAL_VEHICLE: AME_RENTAL_VEHICLE_FIELDS,
  EVACUATION: AME_EVACUATION_FIELDS,
  PA_WEEKLY: AME_PA_WEEKLY_FIELDS,
  PS_WEEKLY: AME_PS_WEEKLY_FIELDS,
  MEDICAL: AME_MEDICAL_FIELDS,
  OTHERS: AME_OTHERS_FIELDS,
};
