import { FieldConfig } from '../../../models/region.model';
import {
  ANZ_BAGGAGE_FIELDS,
  ANZ_CARD_MISUSE_FIELDS,
  ANZ_CORP_EVACUATION_FIELDS,
  ANZ_CORP_MEDICAL_FIELDS,
  ANZ_CORP_PA_WEEKLY_FIELDS,
  ANZ_CORP_PS_WEEKLY_FIELDS,
  ANZ_CORP_RENTAL_VEHICLE_FIELDS,
  ANZ_CORP_TRIP_CANCEL_FIELDS,
  ANZ_OTHERS_FIELDS,
} from './field-sets';

export const ANZ_CORP_TRAVEL_CLAIM_FIELDS: Record<string, FieldConfig[]> = {
  TRIP_CANCEL: ANZ_CORP_TRIP_CANCEL_FIELDS,
  BAGGAGE: ANZ_BAGGAGE_FIELDS,
  RENTAL_VEHICLE: ANZ_CORP_RENTAL_VEHICLE_FIELDS,
  EVACUATION: ANZ_CORP_EVACUATION_FIELDS,
  PA_WEEKLY: ANZ_CORP_PA_WEEKLY_FIELDS,
  PS_WEEKLY: ANZ_CORP_PS_WEEKLY_FIELDS,
  MEDICAL: ANZ_CORP_MEDICAL_FIELDS,
  CARD_MISUSE: ANZ_CARD_MISUSE_FIELDS,
  OTHERS: ANZ_OTHERS_FIELDS,
};
