import { FieldConfig } from '../../../models/region.model';
import {
  ANZ_BAGGAGE_FIELDS,
  ANZ_GENERIC_EVACUATION_FIELDS,
  ANZ_GENERIC_TRIP_CANCEL_FIELDS,
  ANZ_MEDICAL_FIELDS,
  ANZ_OTHERS_FIELDS,
} from './field-sets';

export const ANZ_EXPAT_INPAT_CLAIM_FIELDS: Record<string, FieldConfig[]> = {
  MEDICAL: ANZ_MEDICAL_FIELDS,
  TRIP_CANCEL: ANZ_GENERIC_TRIP_CANCEL_FIELDS,
  BAGGAGE: ANZ_BAGGAGE_FIELDS,
  EVACUATION: ANZ_GENERIC_EVACUATION_FIELDS,
  OTHERS: ANZ_OTHERS_FIELDS,
};
