import { FieldConfig } from '../../../models/region.model';
import {
  ANZ_BAGGAGE_FIELDS,
  ANZ_GENERIC_RENTAL_VEHICLE_FIELDS,
  ANZ_GENERIC_TRIP_CANCEL_FIELDS,
  ANZ_OTHERS_FIELDS,
} from './field-sets';

export const ANZ_LEISURE_TRAVEL_CLAIM_FIELDS: Record<string, FieldConfig[]> = {
  TRIP_CANCEL: ANZ_GENERIC_TRIP_CANCEL_FIELDS,
  BAGGAGE: ANZ_BAGGAGE_FIELDS,
  RENTAL_VEHICLE: ANZ_GENERIC_RENTAL_VEHICLE_FIELDS,
  OTHERS: ANZ_OTHERS_FIELDS,
};
