import { Validators } from '@angular/forms';
import { FieldConfig, RegionFormConfig, RegionName } from '../models/region.model';

export const COUNTRY_REGION_MAP: Record<string, RegionName> = {
  HK: 'AME',
  MO: 'AME',
  SG: 'AME',
  AU: 'ANZ',
  NZ: 'ANZ',
  UK: 'UK',
  GB: 'UK',
};

export const REGION_FORM_CONFIGS: Record<RegionName, RegionFormConfig> = {
  AME: {
    tripInfoFields: [
      {
        name: 'departureDate',
        label: 'Date of Departure / AME-trip',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'reasonForTravel',
        label: 'Reason for Travel',
        type: 'text',
        placeholder: 'Enter reason for travel',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'departureCity',
        label: 'Departure City',
        type: 'text',
        placeholder: 'Enter departure city',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'destinationCity',
        label: 'Destination City',
        type: 'text',
        placeholder: 'Enter destination city',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'destinationCountry',
        label: 'Destination Country',
        type: 'text',
        placeholder: 'Select Country',
      },
      {
        name: 'returnDate',
        label: 'Date of Return',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
    ],
    lossInfoFields: [
      {
        name: 'dateOfLoss',
        label: 'Date of Loss / AME-loss',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'descriptionOfLoss',
        label: 'Description of Loss',
        type: 'textarea',
        placeholder: 'Briefly explain what happened',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'whereDidLossOccur',
        label: 'Where did the loss occur?',
        type: 'select',
        options: [
          { value: 'Hotel', label: 'Hotel' },
          { value: 'Airport', label: 'Airport' },
          { value: 'Taxi', label: 'Taxi' },
          { value: 'Flight', label: 'Flight' },
        ],
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'reportedToBhsi',
        label: 'Was this matter reported to BHSI Care & Concierge?',
        type: 'radio',
        options: [
          { value: 'true', label: 'Yes' },
          { value: 'false', label: 'No' },
        ],
      },
      { name: 'caseNumber', label: 'Case Number', type: 'text', placeholder: 'Enter case number' },
    ],
    contactInfoFields: [
      {
        name: 'isClaimant',
        label: 'Are you the Claimant? / AME-contact',
        type: 'select',
        options: [
          { value: 'YES', label: 'Yes' },
          { value: 'NO', label: 'No' },
        ],
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactName',
        label: 'Contact Name',
        type: 'text',
        placeholder: 'Enter Contact Name',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactPhone',
        label: 'Contact Phone',
        type: 'text',
        placeholder: 'Enter Contact Phone',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactEmail',
        label: 'Contact Email',
        type: 'text',
        placeholder: 'Enter Contact Email',
        required: true,
        validators: [Validators.required],
      },
    ],
  },
  ANZ: {
    tripInfoFields: [
      {
        name: 'departureDate',
        label: 'Date of Departure / ANZ-trip',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'departureCity',
        label: 'Departure City',
        type: 'text',
        placeholder: 'Enter departure city',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'destinationCity',
        label: 'Destination City',
        type: 'text',
        placeholder: 'Enter destination city',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'departureCountry',
        label: 'Departure Country',
        type: 'text',
        placeholder: 'Select Country',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'returnDate',
        label: 'Date of Return',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
    ],
    lossInfoFields: [
      {
        name: 'dateOfLoss',
        label: 'Date of Loss / ANZ-loss',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'lossType',
        label: 'Loss Type',
        type: 'select',
        options: [
          { value: 'Theft', label: 'Theft' },
          { value: 'Accident', label: 'Accident' },
          { value: 'Medical', label: 'Medical' },
        ],
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'descriptionOfLoss',
        label: 'Description of Loss',
        type: 'textarea',
        placeholder: 'Briefly explain what happened',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'whereDidLossOccur',
        label: 'Where did the loss occur?',
        type: 'text',
        placeholder: 'Enter location',
      },
      {
        name: 'reportedToBhsi',
        label: 'Was this matter reported to BHSI Care & Concierge?',
        type: 'radio',
        options: [
          { value: 'true', label: 'Yes' },
          { value: 'false', label: 'No' },
        ],
      },
    ],
    contactInfoFields: [
      {
        name: 'isClaimant',
        label: 'Are you the Claimant? / ANZ-contact',
        type: 'select',
        options: [
          { value: 'YES', label: 'Yes' },
          { value: 'NO', label: 'No' },
        ],
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'claimantName',
        label: 'Claimant Name',
        type: 'text',
        placeholder: 'Enter claimant name',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'claimantMobile',
        label: 'Claimant Mobile',
        type: 'text',
        placeholder: 'Enter claimant mobile',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'claimantEmail',
        label: 'Claimant Email',
        type: 'text',
        placeholder: 'Enter claimant email',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'relationshipToClaimant',
        label: 'Relationship to Claimant',
        type: 'text',
        placeholder: 'Enter relationship',
        required: true,
        validators: [Validators.required],
      },
    ],
  },
  UK: {
    tripInfoFields: [
      {
        name: 'departureDate',
        label: 'Date of Departure / UK-trip',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'reasonForTravel',
        label: 'Reason for Travel',
        type: 'text',
        placeholder: 'Enter reason for travel',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'destinationCity',
        label: 'Destination City',
        type: 'text',
        placeholder: 'Enter destination city',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'destinationCountry',
        label: 'Destination Country',
        type: 'text',
        placeholder: 'Select Country',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'returnDate',
        label: 'Date of Return',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
    ],
    lossInfoFields: [
      {
        name: 'dateOfLoss',
        label: 'Date of Loss / UK-loss',
        type: 'date',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'descriptionOfLoss',
        label: 'Description of Loss',
        type: 'textarea',
        placeholder: 'Briefly explain what happened',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'policeReference',
        label: 'Police Reference',
        type: 'text',
        placeholder: 'Enter police reference number',
      },
      {
        name: 'reportedToBhsi',
        label: 'Was this matter reported to BHSI Care & Concierge?',
        type: 'radio',
        options: [
          { value: 'true', label: 'Yes' },
          { value: 'false', label: 'No' },
        ],
      },
    ],
    contactInfoFields: [
      {
        name: 'isClaimant',
        label: 'Are you the Claimant? / UK-contact',
        type: 'select',
        options: [
          { value: 'YES', label: 'Yes' },
          { value: 'NO', label: 'No' },
        ],
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactName',
        label: 'Contact Name',
        type: 'text',
        placeholder: 'Enter Contact Name',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactPhone',
        label: 'Contact Phone',
        type: 'text',
        placeholder: 'Enter Contact Phone',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactEmail',
        label: 'Contact Email',
        type: 'text',
        placeholder: 'Enter Contact Email',
        required: true,
        validators: [Validators.required],
      },
      {
        name: 'contactAddress',
        label: 'Contact Address',
        type: 'text',
        placeholder: 'Enter contact address',
      },
    ],
  },
};
